# Generated by Django 3.2.9 on 2021-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Booking Reference', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_comments',
            field=models.TextField(blank=True),
        ),
    ]
