# Generated by Django 3.2.9 on 2021-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0006_remove_booking_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_comments',
            field=models.TextField(blank=True, default='Please note any allergies', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Booking Request', max_length=200, unique=True),
        ),
    ]
