# Generated by Django 3.2.9 on 2021-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0008_auto_20211212_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Booking Request', max_length=200),
        ),
    ]
