# Generated by Django 3.2.9 on 2021-12-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0010_auto_20211215_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
